### PR TITLE
Switch to Colors package (do not merge yet)

### PR DESCRIPTION
**Pull request by timholy**
This needs to wait until "C-day" (hopefully this week) before merging. I expect this to show test failures (if you have Travis testing on): doing this right requires coordinated switching across many packages, and so this really shouldn't pass on its own. When it comes time to merge them all, I'll write a test that updates all packages simultaneously and see how all tests fare.

### CODE REVIEW

**Comment by timothyrenner** [comment]
Okay, sounds good - just let me know when to merge. Thanks for taking care of this!

**Comment by timholy** [comment]
It was pretty trivial for me, since I have a script with several `sed` calls that just does almost everything for me.

**Comment by timholy** [comment]
OK, merge away!

**Comment by timothyrenner** [comment]
Alrighty, it's merged and tagged, JuliaLang/METADATA.jl#3167.

**Comment by timholy** [comment]
Awesome, thanks!

**Pull request merged**
