### PR TITLE
support (and test) Julia v0.7 and Julia v1.0

### PR DESCRIPTION
**Pull request by rdeits**

### CODE REVIEW

**Comment by timothyrenner** [comment]
Thanks! Will cut a release soon.

**Comment by tlnagy** [comment]
Bump. Can you please tag a new release when you get a chance?

**Comment by timothyrenner** [comment]
Damn I knew I'd forget :). Doing this right now.

**Comment by timothyrenner** [comment]
Here's the METADATA.jl PR @tlnagy - https://github.com/JuliaLang/METADATA.jl/pull/17866

**Pull request merged**
