### PR TITLE
add `Project.toml` file, add basic CI, support `Colors` 0.13

### PR DESCRIPTION
**Pull request by t-bltg**
Please register the new version after merge, thanks !

Please enable github actions in this repo for CI to run ...

cc @timothyrenner 

Could we maybe move this package to a julia organization (e.g. [JuliaGraphics](https://github.com/JuliaGraphics)) in order to ease maintenance ?

### CODE REVIEW

**Comment by timothyrenner** [comment]
@t-bltg yes, that is a good idea. Let me see if I can figure that out.

**Comment by timothyrenner** [comment]
@t-bltg I need permission to create a repository in JuliaGraphics to transfer it. Is that something you can help me with?

**Comment by t-bltg** [comment]
Great to hear @timothyrenner, if you want you can transfer your repo to me and I will ensure that you have full admin rights once I will have transferred it to the `JuliaGraphics` org ?

**Comment by timothyrenner** [comment]
@t-bltg looks like you'll need to delete your fork for me to transfer this one to you.

**Comment by t-bltg** [comment]
Done !

**Comment by timothyrenner** [comment]
Transfer request sent.

**Comment by t-bltg** [comment]
Thanks, it's now living at https://github.com/JuliaGraphics/ColorBrewer.jl.

Are you able to commit directly there ?

**Comment by ViralBShah** [comment]
@t-bltg gave you ownership here

**Comment by jkrumbiegel** [comment]
Looks like the 0.4.1 version has not been tagged, yet, which holds back Colors in Makie. Is this ready to be registered or was there some other holdup?

**Comment by t-bltg** [comment]
@jkrumbiegel, https://github.com/JuliaRegistries/General/pull/123104.

**Comment by jkrumbiegel** [comment]
@t-bltg perfect, thanks!

**Pull request merged**
